import datetime
import json
import os
from typing import Dict

"""
PSMaker123 - Mock Paystub Generator
PERSONAL / EDUCATIONAL / MOCK USE ONLY
NOT for official tax documents, employment verification, loans, or any legal/financial purpose.

2026 approximate tax rates used (FICA, federal brackets, state flat/average rates).
"""

FICA_RATE = 0.0765  # Social Security 6.2% + Medicare 1.45%

# Approximate 2026 state income tax rates (flat or effective average for mid-income)
# Sources: Tax Foundation, state revenue dept projections, etc. (as of early 2026)
STATE_TAX_RATES = {
    "AL": 5.0,
    "AK": 0.0,
    "AZ": 2.5,
    "AR": 3.9,
    "CA": 8.0,
    "CO": 4.4,
    "CT": 5.0,
    "DE": 5.55,
    "DC": 8.5,
    "FL": 0.0,
    "GA": 5.09,
    "HI": 8.0,
    "ID": 5.695,
    "IL": 4.95,
    "IN": 2.95,
    "IA": 3.9,
    "KS": 5.7,
    "KY": 3.5,
    "LA": 4.25,
    "ME": 5.8,
    "MD": 5.0,
    "MA": 5.0,
    "MI": 4.25,
    "MN": 6.85,
    "MS": 4.0,
    "MO": 4.7,
    "MT": 5.65,
    "NE": 4.55,
    "NV": 0.0,
    "NH": 0.0,
    "NJ": 5.525,
    "NM": 5.0,
    "NY": 6.5,
    "NC": 3.99,
    "ND": 2.5,
    "OH": 2.75,
    "OK": 4.75,
    "OR": 8.0,
    "PA": 3.07,
    "RI": 5.0,
    "SC": 6.0,
    "SD": 0.0,
    "TN": 0.0,
    "TX": 0.0,
    "UT": 4.5,
    "VT": 6.0,
    "VA": 5.75,
    "WA": 0.0,
    "WV": 5.12,
    "WI": 5.0,
    "WY": 0.0
}

# Approximate 2026 federal income tax brackets (single filer)
FEDERAL_BRACKETS_SINGLE = [
    (0, 12400, 0.10),
    (12400, 50400, 0.12),
    (50400, 105700, 0.22),
    (105700, 211400, 0.24),
]

STANDARD_DEDUCTION_SINGLE = 15700  # Approx 2026 single filer

def estimate_annual_federal_tax(annual_gross: float) -> float:
    taxable = max(0, annual_gross - STANDARD_DEDUCTION_SINGLE)
    tax = 0.0
    prev = 0
    for low, high, rate in FEDERAL_BRACKETS_SINGLE:
        segment = min(taxable, high) - max(prev, low)
        if segment > 0:
            tax += segment * rate
        prev = high
    if taxable > prev:
        tax += (taxable - prev) * 0.32  # rough approximation for next bracket
    return tax

def estimate_federal_biweekly(gross_biweekly: float) -> float:
    annual = gross_biweekly * 26
    tax_annual = estimate_annual_federal_tax(annual)
    return round(tax_annual / 26, 2)

def load_ytd() -> Dict[str, float]:
    if os.path.exists("psmaker123_ytd.json"):
        with open("psmaker123_ytd.json", "r") as f:
            return json.load(f)
    return {"gross": 0.0, "net": 0.0, "deductions": 0.0}

def save_ytd(data: Dict[str, float]):
    with open("psmaker123_ytd.json", "w") as f:
        json.dump(data, f, indent=2)

def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

def get_float(prompt: str, default: float = 0.0) -> float:
    while True:
        try:
            val = input(prompt).strip()
            return float(val) if val else default
        except ValueError:
            print("Please enter a valid number.")

def print_step_header(step: int, title: str):
    print(f"\n{'=' * 60}")
    print(f"  STEP {step}/3 : {title.upper()}")
    print(f"{'=' * 60}\n")

def generate_stub_text(data: dict, template_style: str = "Professional") -> str:
    title = f"PSMaker123 - {template_style} Paystub"
    stub = f"""
{title.center(76)}
{'-' * 76}
EMPLOYEE: {data['emp_name']:<40}  PAY DATE: {data['pay_date']:<15}
ID: {data['emp_id']:<10}           PERIOD: {data['period_start']} - {data['period_end']}
ADDRESS: {data['emp_address']}, {data['emp_city']}, {data['emp_state']} {data['emp_zip']}

EMPLOYER: {data['company_name']:<40}  EIN: {data['ein']}
{'-' * 76}
EARNINGS                  | THIS PERIOD     YTD
{'-' * 76}
Hourly Rate: ${data['rate']:.2f}
Regular Hours: {data['reg_hours']:>6.2f}       | ${data['gross_reg']:>10.2f}   ${data['ytd_gross']:>10.2f}
Overtime Hours: {data['ot_hours']:>6.2f}       | ${data['gross_ot']:>10.2f}
GROSS PAY:                             | ${data['gross']:>10.2f}

DEDUCTIONS                | THIS PERIOD
{'-' * 76}
FICA (7.65%):                          | ${data['fica']:>10.2f}
Federal Income Tax:                    | ${data['fed_tax']:>10.2f}
State Tax ({data['state']} ~{data['state_rate']}%):      | ${data['state_tax']:>10.2f}
Other Deductions:                      | ${data['other_ded']:>10.2f}
TOTAL DEDUCTIONS:                      | ${data['total_ded']:>10.2f}

NET PAY THIS PERIOD:                   ${data['net']:>10.2f}

YTD NET PAY:                           ${data['ytd_net']:>10.2f}
{'-' * 76}
Generated by PSMaker123 – Mock Tool Only – Not for Official Use
"""
    return stub

def main():
    clear_screen()
    print("Welcome to PSMaker123 – Mock Paystub Creator")
    print("Inspired by professional online generators | PERSONAL / MOCK USE ONLY\n")
    print("3 steps: 1. Enter Details   2. Preview   3. Generate & Download\n")

    ytd = load_ytd()

    # STEP 1: Input
    print_step_header(1, "Company & Employee Details")
    company_name = input("Company Name: ").strip() or "Sample LLC"
    ein = input("Employer EIN (mock e.g. 12-3456789): ").strip() or "12-3456789"
    emp_name = input("Employee Full Name: ").strip()
    emp_id = input("Employee ID: ").strip() or f"EMP-{abs(hash(emp_name)) % 1000000}"
    emp_address = input("Employee Address: ").strip()
    emp_city = input("City: ").strip()
    emp_state = input("State (2-letter code, e.g. CO): ").strip().upper() or "CO"
    emp_zip = input("ZIP Code: ").strip()

    print("\nPay Schedule")
    pay_date = input("Pay Date (MM/DD/YYYY) [today if blank]: ").strip() or datetime.date.today().strftime("%m/%d/%Y")
    period_start = input("Period Start (MM/DD/YYYY): ").strip()
    period_end = input("Period End (MM/DD/YYYY): ").strip()

    print_step_header(1, "Earnings & Hours")
    rate = get_float("Hourly Rate ($): ", 22.00)
    reg_hours = get_float("Regular Hours: ", 80.0)
    ot_hours = get_float("Overtime Hours (1.5x): ", 0.0)
    other_earnings = get_float("Other Earnings (bonus, etc.): ", 0.0)

    gross_reg = reg_hours * rate
    gross_ot = ot_hours * rate * 1.5
    gross = round(gross_reg + gross_ot + other_earnings, 2)

    print_step_header(1, "Taxes & Deductions")
    filing = input("Filing Status (single/married) [single]: ").strip().lower() or "single"
    other_ded = get_float("Other Deductions (401k, health, etc.): ", 0.0)
    manual_taxes = input("Enter taxes manually? (y/n) [n]: ").strip().lower() == 'y'

    fica = round(gross * FICA_RATE, 2)
    state_rate_pct = STATE_TAX_RATES.get(emp_state, 4.0)
    state_rate = state_rate_pct / 100
    state_tax = round(gross * state_rate, 2)

    if manual_taxes:
        fed_tax = get_float("Federal Income Tax ($): ", 0.0)
        state_tax = get_float("State Income Tax ($): ", state_tax)
    else:
        fed_tax = estimate_federal_biweekly(gross)

    total_ded = round(fica + fed_tax + state_tax + other_ded, 2)
    net = round(gross - total_ded, 2)

    ytd_gross = round(ytd["gross"] + gross, 2)
    ytd_ded = round(ytd["deductions"] + total_ded, 2)
    ytd_net = round(ytd["net"] + net, 2)

    data = {
        "emp_name": emp_name,
        "emp_id": emp_id,
        "emp_address": emp_address,
        "emp_city": emp_city,
        "emp_state": emp_state,
        "emp_zip": emp_zip,
        "company_name": company_name,
        "ein": ein,
        "pay_date": pay_date,
        "period_start": period_start,
        "period_end": period_end,
        "rate": rate,
        "reg_hours": reg_hours,
        "ot_hours": ot_hours,
        "gross_reg": gross_reg,
        "gross_ot": gross_ot,
        "gross": gross,
        "fica": fica,
        "fed_tax": fed_tax,
        "state_tax": state_tax,
        "state_rate": state_rate_pct,
        "other_ded": other_ded,
        "total_ded": total_ded,
        "net": net,
        "ytd_gross": ytd_gross,
        "ytd_net": ytd_net
    }

    # STEP 2: Preview
    clear_screen()
    print_step_header(2, "Paystub Preview")
    template = input("Template style (Professional / Modern / Simple) [Professional]: ").strip() or "Professional"
    preview = generate_stub_text(data, template)
    print(preview)

    # STEP 3: Download
    confirm = input("\nGenerate & Download paystub? (y/n): ").strip().lower()
    if confirm == 'y':
        filename = f"PSMaker123_{pay_date.replace('/', '-')}.txt"
        with open(filename, "w", encoding="utf-8") as f:
            f.write(preview)

        save_ytd({"gross": ytd_gross, "net": ytd_net, "deductions": ytd_ded})

        clear_screen()
        print_step_header(3, "Success!")
        print(f"Paystub downloaded as: {filename}")
        print("Year-to-date totals updated and saved.")
        print("\nThank you for using PSMaker123 – mock tool only!\n")
    else:
        print("Cancelled. Run the script again when ready.")

if __name__ == "__main__":
    main()
